---
- name: "Otomasyonu çalıştır | diskefesdv"
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - name: Örnek görevi çalıştır
      ansible.builtin.debug:
        msg: "disk otomasyon iskeleti hazır"
